project:
  name: Fantasy Bakery
  description: |
    Un e-commerce encantado para la venta de panader칤a m치gica. Incluye cat치logo de productos,
    carrito de compras, integraci칩n con Firebase y visuales en tonos menta y rosa.
  version: 1.0.0
  authors:
    - name: Liliana Hern치ndez/Coderhouse/Chat GPT sobre todo para cuando uno la reg칩. 
      role: Fullstack Developer & Dise침adora del Proyecto
      email: hernandez.velasco.liliana@gmail.com
  stack:
    frontend:
      - React 18
      - Bootstrap 5
      - Vite
    backend:
      - Firebase Firestore
      - Firebase Hosting
  features:
    - Vista de productos por categor칤a (Top10, Productos, Ofertas)
    - Detalle por producto
    - Carrito de compras
    - Checkout con validaci칩n
    - Confirmaci칩n con ID de orden en Firebase
    - Carga autom치tica de productos con Upload
  status: En desarrollo activo 游뚾
  license: MIT
